services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV_STATE=prod
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: kolang
      TZ: Asia/Seoul
    expose:
        - "3306"
    command:
        - --skip-character-set-client-handshake
    volumes:
        - ./db_data:/var/lib/mysql
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db_data: